# Site settings
title: Naveen Kumar H N
email: mailme@naveenhn.in
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://naveenhn.in" # the base hostname & protocol for your site
twitter_username: naveenhn
github_username:  naveen

# Build settings
markdown: kramdown
paginate: 3


# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

#include _pages folder
include: ['_pages']

gems: [jekyll-paginate]

# Markdown Processors
kramdown:
  input: GFM
